name: check format
on:
  pull_request:


jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v4
      - run: gofmt -d .
