name: check format
on:
  pull_request:


jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
      - name: check gofmt
        run: |
          gofmt_result=$(gofmt -l .)
          if [ -n "$gofmt_result" ]; then
            gofmt -d .
            exit 1
          fi
      - name: lint
        run: go vet ./...
